### ISSUE TITLE
Implémenter l'initialisation de l'application

### ISSUE THREAD

**Issue by KierannCode** [KierannCode/GameRef#5]
L'application doit initialiser la base de données selon la consigne suivante :
>Écrire les contrôleurs Spring pour votre application Web. Le contrôleur InitController doit contenir une méthode qui ajoute deux objets de chacune des classes suivantes : Editeur, Classification (exemples : PEGI 12, PEGI 16), Genre (exemple : FPS), Plateforme (exemples : Switch, PS5), ModeleEconomique (exemples : free to play, pay to play), Joueur, Modérateur et Jeu.

**Comment by KierannCode** [comment]
Nécessaire pour l'initialisation : implémentation d'une méthode d'ajout pour tous les services et des dto de création pour toutes les classes métier

**Comment by jperaudon** [comment]
Ajout de l'initialisation des Jeux.
Changement de l'```InitController```, en ajoutant un méthode ```InitAll``` qui s'occupe d'appeler toutes les autres méthodes au sein du controlleur.

**Comment by PashwamrooCoders** [comment]
Ajout initialisation des Jeux , 
Methodes initPlayers() et initModerators() pour ajouter des joueurs et des moderateurs
